### PR TITLE
Redefining permutation parser interface

### LINKED ISSUE #33: Control.Applicative.Permutations doesn't work with Applicative-only parsers
`Control.Applicative.Permutations.runPermutation` requires that the parser type be a `Monad` for performance.  This is highly surprising when Control.Applicative.Combinators, in contrast, is willing to make some performance sacrifices in order to stay compatible with parsers with no Monad instance.

This isn't a purely theoretical concern. Unless I really need context-sensitivity, I like the Earley package because I don't need to work around the expressiveness limits in the parsec family of libraries. Because the Earley algorithm is restricted to context-free grammars, it doesn't provide a `Monad` instance for its `Prod` type. (It provides a `Grammar` type with a `Monad` instance, but don't let that distract. That type doesn't have an `Alternative` instance, as it's not actually a parsing type. It's only there as a tool for observable sharing.)

The original paper the module documentation links to provides an algorithm that doesn't need a `Monad` instance. It would be consistent with the way the other Applicative/Monad modules split if this module didn't require the `Monad` instance either. And it would make Control.Applicative.Permutations work with Earley.

### PR DESCRIPTION
**Pull request by recursion-ninja**
I updated the `Control.Applicative.Permutations` module to only require an `Applicative` instance. This required a complete rewrite of the underlying code and data structures. As a result the code in this module may be less performant than previously so I have marked this as a breaking change in the `CHANGELOG.md` and `parser-combinators.cabal` files with a version  bump to `1.3.0`.

Since the original code is potentially more efficient depending on the underlying parser, I took that permutation parser code which relied on `Monad` instances and added it to the new module `Control.Monad.Permutations`. This is in line with the design philosophy of the `parser-combinators` library, as I understand it.

Close #33.

### CODE REVIEW

**Comment by mrkkrp** [comment]
It looks like the new code does not behave in the same way:

https://github.com/mrkkrp/parser-combinators/pull/34/checks?check_run_id=1817381898#step:11:200

@recursion-ninja Is this expected?

**Comment by recursion-ninja** [comment]
@mrkkrp no, that's not expected. Let me look into this.

**Comment by recursion-ninja** [comment]
@mrkkrp It turns out that there was a subtle defect in the existing monadic permutation parser. If the permutation was searching for `"a,b,c"` with default values `"x,y,z"` and encountered `"a,b,x"`, the permutation parser would *consume* the second `','` and *succeed* by returning the default value `z` in place of `c`. This behavior is incorrect.

The desired behavior is that if an effect/separator that occurs between permutation components is encountered, there must immediately be a permutation component following it or else the parser should fail.

For example:
| Input | Output |
|:---|:--|
| `"a,b,q"` | Failed! Expected `'c'` after `"a,b,"`|
| `"a,bq"` | Success! Result `('a','b',z')`|

The incorrect behavior was specified in the test suite. I corrected the functionality in the `Applicative` and `Monad` versions of the permutation parser and updated the test suite to reflect corrected behavior.

File: parser-combinators-tests/tests/Control/Applicative/PermutationsSpec.hs [hunk 1]
```diff
@@ -44,7 +45,7 @@ spec = do
            in prsp (pure f <*> pure (x :: Int)) ""
                 === prsp (pure (f x)) ""
       it "obeys interchange law" $
-        property $ \n y ->
+65;6003;1c        property $ \n y ->
```
Comment (mrkkrp) [inline parser-combinators-tests/tests/Control/Applicative/PermutationsSpec.hs:48]: I believe this breaks the build.

**Review by mrkkrp — CHANGES_REQUESTED** [review]

File: parser-combinators-tests/tests/Control/Applicative/PermutationsSpec.hs (hunk 1 above)
Comment (recursion-ninja) [reply parser-combinators-tests/tests/Control/Applicative/PermutationsSpec.hs]: Some emacs artifact. I've removed it!
